### ISSUE TITLE
Minor: duplicate text in archetype generation in interactive mode

### ISSUE THREAD

**Issue by ljnelson** [oracle/helidon-build-tools#362] opened 2021-03-02 15:43 UTC
I generated an MP project using the MP quickstart archetype in interactive mode.

The confirmation stage presented me with two copies of every item:
```
Define value for property 'groupId': io.github.ljnelson.helidon.example 
[INFO] Using property: groupId = io.github.ljnelson.helidon.example
Define value for property 'artifactId': helidon-example-mp-config
[INFO] Using property: artifactId = helidon-example-mp-config
[INFO] Using property: version = 1.0-SNAPSHOT
Define value for property 'package' io.github.ljnelson.helidon.example: : 
[INFO] Using property: package = io.github.ljnelson.helidon.example
[INFO] Using property: name = myproject
Confirm properties configuration:
groupId: io.github.ljnelson.helidon.example
groupId: io.github.ljnelson.helidon.example
artifactId: helidon-example-mp-config
artifactId: helidon-example-mp-config
version: 1.0-SNAPSHOT
package: io.github.ljnelson.helidon.example
package: io.github.ljnelson.helidon.example
name: myproject
 Y: : 
```

Haven't looked to see if this is the archetype plugin's fault or ours.

**Comment by romain-grecourt** [comment] 2022-07-15 07:37
TODO verify that this also impacts v3 and triage accordingly

**Comment by romain-grecourt** [comment] 2022-07-15 19:11
This output is coming from the maven archetype plugin itself. At this stage the archetype is not yet invoked.

```
Confirm properties configuration:
groupId: com.example
artifactId: myproject
version: 1.0-SNAPSHOT
name: myproject
package: com.example
groupId: com.example
artifactId: myproject
package: com.example
 Y: : 
[INFO] ----------------------------------------------------------------------------
[INFO] Using following parameters for creating project from Archetype: helidon-quickstart-se:2.5.1
[INFO] ----------------------------------------------------------------------------
```

The archetype is actually invoked after the confirmation prompt.
In the case of Helidon Maven compatible archetypes, our archetype engine gets executed when you see this line:

```
Executing META-INF/archetype-post-generate.groovy post-generation script
```

This is likely a bug that has to do with the Maven used or the `maven-archetype-plugin` version used.
Or perhaps this is caused by some bad archetype XML? Either I cannot reproduce with either 2.x or 3.x ; closing.

**Closed by romain-grecourt** 2022-07-15 19:11 UTC
Labels: bug, archetype
